---
# tasks file for deploy_flask
- name: Install unzip on target server
  package:
    name: unzip
    state: present

- name: Ensure /opt/secureapp directory exists
  file:
    path: /opt/secureapp
    state: directory
    mode: '0755'

- name: Unzip Flask app
  unarchive:
    src: /tmp/secureapp.zip
    dest: /opt/secureapp
    remote_src: yes

- name: Create Python virtual environment and bootstrap pip
  shell: |
    python3 -m venv /opt/secureapp/venv
    /opt/secureapp/venv/bin/python -m ensurepip --upgrade
  args:
    creates: /opt/secureapp/venv/bin/activate

- name: Install Python dependencies from requirements.txt
  command: /opt/secureapp/venv/bin/pip install -r /opt/secureapp/app/requirements.txt
  register: pip_install
  failed_when: pip_install.rc != 0

- name: Show pip install output
  debug:
    msg: "{{ pip_install.stdout }}"

#- name: Stop nginx if running (optional cleanup)
#  systemd:
#    name: nginx
#    state: stopped
#    enabled: false
#  ignore_errors: true
#  become: true

- name: Create Gunicorn systemd service for secureapp
  copy:
    dest: /etc/systemd/system/secureapp.service
    content: |
      [Unit]
      Description=Gunicorn instance to serve secureapp
      After=network.target

      [Service]
      User=ubuntu
      Group=www-data
      WorkingDirectory=/opt/secureapp/app
      ExecStart=/opt/secureapp/venv/bin/gunicorn -w 3 -b 127.0.0.1:5000 app:app &
      Restart=always

      [Install]
      WantedBy=multi-user.target
  become: true

- name: Reload systemd daemon
  command: systemctl daemon-reexec
  become: true

- name: Enable and start Gunicorn service
  systemd:
    name: secureapp
    enabled: true
    state: started
  become: true


# Gunicorn is bound to 127.0.0.1 to restrict access to the local server only.
# This ensures the Flask app is not exposed directly to the internet.
# Nginx acts as a reverse proxy, securely forwarding HTTPS traffic to Gunicorn.
# This setup improves security and allows Nginx to manage SSL termination.
# where you are at cd location determins app:app:app
...