---
# tasks file for verify_artifact,make url for download dynamic the job number changes
- name: Download secureapp.zip from Jenkins (build #5)
  get_url:
    url: "http://54.221.3.207:8080/job/secureapp/5/artifact/secureapp.zip"
    dest: "/tmp/secureapp.zip"
    url_username: secureapp
    url_password: "Password1$"
    force_basic_auth: yes

- name: Download hash.txt from Jenkins (build #5)
  get_url:
    url: "http://54.221.3.207:8080/job/secureapp/5/artifact/hash.txt"
    dest: "/tmp/hash.txt"
    url_username: secureapp
    url_password: "Password1$"
    force_basic_auth: yes

- name: Compute SHA-256 hash of artifact
  stat:
    path: /tmp/artifact.zip
    checksum_algorithm: sha256
  register: artifact_stat

- name: Fail if hash does not match
  fail:
    msg: "Artifact integrity check failed. Expected hash does not match actual."
  when: artifact_stat.stat.checksum != "expected_sha256_hash_here"
...