---
# tasks file for verify_artifact

- name: Download secureapp-latest.zip from Jenkins
  get_url:
    url: "http://3.85.4.177:8080/job/secureapp/lastSuccessfulBuild/artifact/secureapp-latest.zip"
    dest: "/tmp/secureapp.zip"
    url_username: "{{ url_username }}"
    url_password: "{{ url_password }}"
    force_basic_auth: yes

- name: Download hash-latest.txt from Jenkins
  get_url:
    url: "http://3.85.4.177:8080/job/secureapp/lastSuccessfulBuild/artifact/hash-latest.txt"
    dest: "/tmp/hash.txt"
    url_username: "{{ url_username }}"
    url_password: "{{ url_password }}"
    force_basic_auth: yes

- name: Verify SHA-256 hash from /tmp directory
  command: sha256sum -c hash.txt
  args:
    chdir: /tmp
  register: hash_check
  failed_when: "'OK' not in hash_check.stdout"
